# Generated by Django 2.2.5 on 2019-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название склада')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Размеры помещения (высота)')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размеры помещения')),
                ('optimumTemperature', models.IntegerField(blank=True, null=True, verbose_name='Температура склада')),
                ('typeProduct', models.CharField(choices=[('Сухие товары', 'Сухие товары'), ('Скоропортящиеся товары', 'Скоропортящиеся товары'), ('Хрупкие товары', 'Хрупкие товары')], default='Грузчик', max_length=30, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
    ]
