# Generated by Django 2.2.5 on 2019-09-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseSpace', '0002_auto_20190928_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousespace',
            name='sizeGr',
        ),
    ]
