# Generated by Django 2.2.5 on 2019-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseSpace', '0003_remove_warehousespace_sizegr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousespace',
            name='typeProduct',
            field=models.CharField(choices=[('Сухие товары', 'Сухие товары'), ('Скоропортящиеся товары', 'Скоропортящиеся товары'), ('Хрупкие товары', 'Хрупкие товары')], default='Сухие товары', max_length=30, verbose_name='Тип склада'),
        ),
    ]
