# Generated by Django 2.2.5 on 2019-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseSpace', '0004_auto_20191005_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousespace',
            name='secToPal',
            field=models.IntegerField(default=12, verbose_name='Секунд на разгрузку 1 паллету'),
        ),
    ]
