# Generated by Django 2.2.5 on 2019-10-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutPalletAll', models.IntegerField(blank=True, null=True, verbose_name='Кол-во паллет')),
            ],
        ),
    ]
