# Generated by Django 2.2.5 on 2019-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота стелажа (Одной полки)')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размер')),
                ('countShelf', models.IntegerField(blank=True, null=True, verbose_name='Количество полок')),
            ],
            options={
                'verbose_name': 'Стелаж',
                'verbose_name_plural': 'Стелаж',
            },
        ),
    ]
