# Generated by Django 2.2.5 on 2019-09-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelving', '0002_auto_20190928_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelving',
            name='kg_polki',
            field=models.IntegerField(blank=True, null=True, verbose_name='нагрузка на ярус, кг'),
        ),
    ]
