# Generated by Django 2.2.5 on 2019-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelving', '0003_shelving_kg_polki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelving',
            name='kg_polki',
            field=models.IntegerField(blank=True, null=True, verbose_name='нагрузка, кг'),
        ),
    ]
