# Generated by Django 2.2.5 on 2019-09-20 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=30, verbose_name='ФИО')),
                ('workWith', models.DateField(blank=True, null=True, verbose_name='Работает с')),
                ('hoursModifier', models.IntegerField(blank=True, null=True, verbose_name='Норма-часов (модификатор)')),
                ('position', models.CharField(choices=[('Грузчик', 'Грузчик'), ('Администратор', 'Администратор')], default='Грузчик', max_length=30, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
    ]
