# Generated by Django 2.2.5 on 2019-10-05 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WarehouseSpace', '0004_auto_20191005_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegister', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата регистрации')),
                ('dateUpload', models.DateTimeField(blank=True, null=True, verbose_name='Дата прибыия')),
                ('timeProc', models.IntegerField(blank=True, null=True, verbose_name='Дата оканчания')),
                ('coutPalletAll', models.IntegerField(blank=True, null=True, verbose_name='Кол-во паллет')),
                ('status', models.CharField(choices=[('Отправлен', 'Отправлен'), ('Прибыл', 'Прибыл'), ('Принят', 'Принят'), ('Отменен', 'Отменен')], default='Отправлен', max_length=30, verbose_name='Статус')),
                ('sklad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarehouseSpace.WarehouseSpace', verbose_name='На склад')),
            ],
            options={
                'verbose_name': 'Грузопоток',
                'verbose_name_plural': 'Грузопоток',
            },
        ),
    ]
