# Generated by Django 2.2.5 on 2019-10-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Юр.лицо'),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='timeProc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Часов на разгрузку'),
        ),
    ]
