# Generated by Django 2.2.5 on 2019-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20191005_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прибытия'),
        ),
    ]
