# Generated by Django 2.2.5 on 2019-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20191006_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='timeProc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Минут на разгрузку'),
        ),
    ]
