# Generated by Django 2.2.5 on 2019-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20191006_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='dateArrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемое прибытие'),
        ),
    ]
