# Generated by Django 2.2.5 on 2019-10-11 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegister', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата регистрации')),
                ('dateArrival', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемое время начала разгрузки')),
                ('dateUpload', models.DateTimeField(blank=True, null=True, verbose_name='Дата разгрузки')),
                ('timeProc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Минут на разгрузку')),
                ('status', models.CharField(choices=[('Ожидание', 'Ожидание'), ('Загрузка', 'Загрузка'), ('Отправлен', 'Отправлен')], default='Ожидание', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Разгрузка',
                'verbose_name_plural': 'Разгрузка',
            },
        ),
    ]
