# Generated by Django 2.2.5 on 2019-10-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unloader',
            name='coutPalletAll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во паллет'),
        ),
        migrations.AddField(
            model_name='unloader',
            name='loads',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Загрузка'),
        ),
    ]
