# Generated by Django 2.2.5 on 2019-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название техники')),
                ('timeUse', models.IntegerField(blank=True, null=True, verbose_name='Минут использования за сегодня')),
                ('HoursDay', models.IntegerField(blank=True, null=True, verbose_name='Норма часов в день')),
                ('allHours', models.IntegerField(blank=True, null=True, verbose_name='Ресурс использования')),
                ('typeTransport', models.CharField(choices=[('Сухие товары', 'Сухие товары'), ('Скоропортящиеся товары', 'Скоропортящиеся товары'), ('Хрупкие товары', 'Хрупкие товары')], default='Сухие товары', max_length=30, verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
