# Generated by Django 2.2.5 on 2019-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='HoursDay',
            field=models.IntegerField(blank=True, default=8, null=True, verbose_name='Норма часов в день'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='allHours',
            field=models.IntegerField(blank=True, default=6400, null=True, verbose_name='Ресурс использования в часах'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='timeUse',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Минут использования за сегодня'),
        ),
    ]
