# Generated by Django 2.2.5 on 2019-10-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20191006_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='dateEditStatus',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения статуса'),
        ),
        migrations.AddField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('Простой', 'Простой'), ('Используется', 'Используется')], default='Простой', max_length=30, verbose_name='Статус использования'),
        ),
    ]
