# Generated by Django 2.2.5 on 2019-10-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20191006_1109'),
        ('transport', '0003_auto_20191006_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='unloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic.Traffic', verbose_name='Разгружает грузопоток'),
        ),
    ]
