# Generated by Django 2.2.5 on 2019-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transport_unloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='allHoursUse',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Используется часов'),
        ),
    ]
