# Generated by Django 2.2.5 on 2019-10-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transport_allhoursuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='coutPallet',
            field=models.IntegerField(blank=True, default=4000, null=True, verbose_name='Кол-во паллет вместимость (только для грузовиков)'),
        ),
    ]
