# Generated by Django 2.2.5 on 2019-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transport_coutpallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='bTrucker',
            field=models.BooleanField(default=False, verbose_name='Это грузовик'),
        ),
    ]
