# Generated by Django 2.2.5 on 2019-10-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unload', '0002_auto_20191011_2030'),
        ('transport', '0007_transport_btrucker'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='unloadsTr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unload.Unloader', verbose_name='Разгружает грузопоток'),
        ),
    ]
