# Generated by Django 2.2.5 on 2019-09-21 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('optimumTemperature', models.IntegerField(blank=True, null=True, verbose_name='Оптимальная температура товара')),
                ('shelfLife', models.DateTimeField(blank=True, null=True, verbose_name='Срок годности до')),
                ('dateUpload', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата загрузки')),
                ('dateUnUpload', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата разгрузки')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукт',
            },
        ),
    ]
