# Generated by Django 2.2.5 on 2019-09-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseSpace', '0001_initial'),
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='sklad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarehouseSpace.WarehouseSpace', verbose_name='Склад'),
        ),
    ]
