# Generated by Django 2.2.5 on 2019-10-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
        ('products', '0005_product_countpallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='traffic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic.Traffic', verbose_name='Грузопоток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateUnUpload',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разгрузки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateUpload',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
    ]
