# Generated by Django 2.2.5 on 2019-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191005_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, default=1500, null=True, verbose_name='Высота паллета'),
        ),
    ]
