# Generated by Django 2.2.5 on 2019-10-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unload', '0001_initial'),
        ('products', '0007_product_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Unloader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unload.Unloader', verbose_name='Грузопоток разгрузки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Отправлен', 'Отправлен'), ('В обработке', 'В обработке'), ('Принят', 'Принят'), ('Отменен', 'Отменен'), ('Загрузка', 'Загрузка')], default='Отправлен', max_length=30, verbose_name='Статус'),
        ),
    ]
